### ISSUE TITLE
Not Generating SQL

### ISSUE THREAD

**Issue by Boyink** [proimage/EE1-Upgrade-nGen-File-Fields#1]
Here are the details - let me know if there is something I'm forgetting:
PHP Version 5.5.9-1ubuntu4.6
ExpressionEngine 1.7.1 
FieldFrame v 1.4
Matrix 1.5
nGen v 1.0.1
Hosted at ArcusTech

![boyink1](https://cloud.githubusercontent.com/assets/71558/6494831/82685e9e-c292-11e4-8873-a58e491a295d.png)
![boyink2](https://cloud.githubusercontent.com/assets/71558/6494832/826ad4b2-c292-11e4-8030-c689e3d8b1e1.png)

MSM
FieldFrame/Matrix - nGen File Field used in Matrix

**Comment by Boyink** [comment]
![template_settings](https://cloud.githubusercontent.com/assets/71558/6494913/3a436e1e-c293-11e4-9f3f-444885625c98.png)

**Comment by proimage** [comment]
Ok, first of all, add this at the top of the PHP... line 39 is fine:
`defined('BR') or define('BR', '<br>');`

Second, what level of error reporting is your PHP set to? I have a feeling there's some crucial error we're not being shown...

EDIT: Third, do you have any nGen fields that aren't in Matrix fields? Any that are?

**Comment by Boyink** [comment]
OK, added, that issue is gone but no SQL statements appear.

Error reporting - I have EE set to show all errors to everyone (this is on a test environment) but I also see under PHP info that display_errors is off. Trying to figure out how to do that - an initial attempt at an htaccess method didn't work.

I have 2 nGen fields that are in Matrix, none that are not.

**Comment by Boyink** [comment]
OK - I edited index.php to add error reporting and now get:

Deprecated: Function ereg() is deprecated in /storage/av02651/www/public_html/index.php on line 118

Not sure if it's helpful or a rabbit trail.

**Comment by proimage** [comment]
Hmm... On a whim, could you create a single non-Matrix nGen file field somewhere? I'm wondering if my derpy PHP skills made it somehow dependent on the presence of a non-Matrix file field. :-/

**Comment by Boyink** [comment]
Well, progress. I added an nGen field outside of Matrix and now get this:

```
MySQL ERROR:
```

Error Number: 1064

Description: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3

Query: SELECT id, name, server_path FROM `exp_upload_prefs` WHERE id =

**Comment by Boyink** [comment]
(The cutoff is accurate to what's loading on the page)

**Comment by proimage** [comment]
Hmm. Pardon if I'm asking the obvious, but do you have a valid upload destination selected?

**Comment by Boyink** [comment]
Ah - sorry. I've been at half mast today with allergies. You're right - I hadn't selected one.  Now I'm getting results for that field, but the SQL statements for the nGen fields in the matrix fields are empty.

**Comment by proimage** [comment]
Ok, I'm pretty sure the problem is due to different matrix versions. My test bed site is running FieldFrame 1.4.5 (probably not a huge change from your 1.4), and Matrix 1.3.5. IIRC that's the last free version Brandon released, and I'm not sure I have a copy anywhere to see what changed. :-/

**Comment by Boyink** [comment]
Ah...OK. I'll plow forward in a less automated fashion. Thanks for the time!

**Comment by proimage** [comment]
Yeah, sorry about that... I completely forgot that there was a paid version of Matrix for EE1. I'll update the repo info accordingly.
